import "./globals.css";
import type { Metadata } from "next";
import { Sidebar } from "./components/Sidebar";
import { Profile } from "./components/Profile";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja" className="w-full h-full">
      <head>
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@24,400,0,0"
        />
      </head>
      <body className="h-full w-full">
        <div className="flex h-full justify-center">
          <section className="container max-w-fit">
            <Sidebar />
          </section>
          <section className="container max-w-2xl">{children}</section>
          <section className="container hidden xl:inline-block xl:max-w-md ">
            <Profile />
          </section>
        </div>
      </body>
    </html>
  );
}
